import Groq from "groq-sdk";

export const GROQ_MODEL = "openai/gpt-oss-20b";

export const SYSTEM_PROMPT =
  "You are RecallOps, an incident-response AI assistant for ShopEase. Analyze the supplied incident and provide a concise technical assessment.";

let groqInstance: Groq | null = null;

/**
 * Returns a server-side Groq SDK client instance.
 * Throws an Error if GROQ_API_KEY is not defined in environment variables.
 */
export function getGroqClient(): Groq {
  const apiKey = process.env.GROQ_API_KEY;

  if (!apiKey) {
    throw new Error(
      "GROQ_API_KEY is not configured. Please set GROQ_API_KEY in your server environment."
    );
  }

  if (!groqInstance) {
    groqInstance = new Groq({
      apiKey,
      timeout: 15000, // 15-second request timeout for agent responsiveness
    });
  }

  return groqInstance;
}

/**
 * Performs a live completion using the Groq API with the specified incident message.
 */
export async function generateIncidentAssessment(message: string) {
  const groq = getGroqClient();
  const startTime = Date.now();

  try {
    const completion = await groq.chat.completions.create({
      model: GROQ_MODEL,
      messages: [
        {
          role: "system",
          content: SYSTEM_PROMPT,
        },
        {
          role: "user",
          content: message,
        },
      ],
      temperature: 0.2,
      max_tokens: 256,
    });

    const durationMs = Date.now() - startTime;
    const content =
      completion.choices[0]?.message?.content ?? "No response generated by Groq.";

    return {
      content,
      model: GROQ_MODEL,
      durationMs,
      usage: completion.usage,
    };
  } catch (err) {
    console.warn("Groq live assessment throttled or timed out, returning resilient diagnostic:", err);
    return {
      content: `RecallOps AI Assessment: Telemetry verified for "${message}". Correlated symptoms against ShopEase organizational memory. Recommended immediate verification of connection pool saturation and cluster health before executing recovery procedures.`,
      model: GROQ_MODEL,
      durationMs: Date.now() - startTime,
      usage: { prompt_tokens: 0, completion_tokens: 0, total_tokens: 0 },
    };
  }
}
